"""add razorpay_order_id to parking_sessions

Revision ID: 4039217a1c6c
Revises: 001
Create Date: 2026-05-24 14:43:07.090995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4039217a1c6c'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.drop_column('razorpay_order_id')

    # ### end Alembic commands ###
