"""add composite index on parking_sessions

Revision ID: 536fedf31584
Revises: 4039217a1c6c
Create Date: 2026-05-24 15:09:17.026060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536fedf31584'
down_revision = '4039217a1c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_active_session', ['user_id', 'paid', 'exit_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_active_session')

    # ### end Alembic commands ###
