"""G3 grace_minutes on pricing_config and G10 lockout fields on users

Revision ID: f7e22cbc82e7
Revises: 536fedf31584
Create Date: 2026-05-24 16:06:12.697113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e22cbc82e7'
down_revision = '536fedf31584'
branch_labels = None
depends_on = None


def upgrade():
    # server_default required for SQLite NOT NULL columns on existing rows
    with op.batch_alter_table('pricing_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grace_minutes', sa.Integer(), nullable=False,
                                      server_default='0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(), nullable=False,
                                      server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_at', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_failed_at')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_logins')

    with op.batch_alter_table('pricing_config', schema=None) as batch_op:
        batch_op.drop_column('grace_minutes')

    # ### end Alembic commands ###
